@startuml
"Procedure" <|-- "ActuatingProcedure"
"Procedure" <|-- "ObservingProcedure"
"Procedure" <|-- "SamplingProcedure"
"Execution" <|-- "Actuation"
"Execution" <|-- "Observation"
"Execution" <|-- "Sampling"
"ExecutionCollection" <|-- "ActuationCollection"
"ExecutionCollection" <|-- "ObservationCollection"
"ExecutionCollection" <|-- "SamplingCollection"
"System" <|-- "Actuator"
"System" <|-- "Sensor"
"System" <|-- "Sampler"
"Asset" <|-- "Platform"
"Asset" <|-- "System"
"Property" <|-- "ActuatableProperty"
"Property" <|-- "ObservableProperty"
"Sample" <|-- "MaterialSample"
"Sample" <|-- "SpatialSample"
"Sample" <|-- "StatisticalSample"
@enduml