@startuml
Property <|-- ActuatableProperty
Sample <|-- MaterialSample
Sample <|-- SpatialSample
Sample <|-- StatisticalSample
Property <|-- ObservableProperty
Procedure <|-- ActuatingProcedure
Procedure <|-- ObservingProcedure
Procedure <|-- SamplingProcedure
Asset <|-- Platform
System <|-- Sampler
System <|-- Actuator
Asset <|-- System
Execution <|-- Sampling
ExecutionCollection <|-- SamplingCollection
Execution <|-- Actuation
System <|-- Sensor
ExecutionCollection <|-- ActuationCollection
ExecutionCollection <|-- ObservationCollection
Execution <|-- Observation
class Input
class Property
class Deployment
class Result
class FeatureOfInterest
class Output
class Stimulus
class System
class Deployment
class SampleCollection
class Stimulus
@enduml