@startuml
Property <|-- ActuatableProperty
Property <|-- ObservableProperty
Sample <|-- MaterialSample
Sample <|-- SpatialSample
Sample <|-- StatisticalSample
Procedure <|-- ActuatingProcedure
Procedure <|-- ObservingProcedure
Procedure <|-- SamplingProcedure
Asset <|-- Platform
Asset <|-- System
System <|-- Sampler
System <|-- Actuator
System <|-- Sensor
ExecutionCollection <|-- SamplingCollection
ExecutionCollection <|-- ActuationCollection
ExecutionCollection <|-- ObservationCollection
Execution <|-- Sampling
Execution <|-- Actuation
Execution <|-- Observation
class Stimulus
class Result
class SampleCollection
class FeatureOfInterest
class Deployment
@enduml